### ISSUE TITLE
Halp, npm start fails 

### ISSUE THREAD

**Issue by r2r2r2** [TheSkorm/osu-soundboxing-importer#1]
Error: Cannot find module 'C:\Users\koivu\index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "C:\\Users\\koivu\\node_modules\\soundboxing-hacking"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! soundboxing-hacking@1.0.0 start: `node index.js "C:\Users\koivu\node_modules\soundboxing-hacking"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soundboxing-hacking@1.0.0 start script 'node index.js "C:\Users\koivu\node_modules\soundboxing-hacking"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the soundboxing-hacking package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js "C:\Users\koivu\node_modules\soundboxing-hacking"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs soundboxing-hacking
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls soundboxing-hacking
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\koivu\npm-debug.log

**Comment by TheSkorm** [comment]
Are you working from the same folder as the code? Looks like index.js is missing
